version: '3.4'

networks:
  my-network:
    driver: bridge

volumes:
  sql-data: 

services:
  db:
    container_name: 'sqlserver'
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "Sina_Razavi123"
       ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/lib/sqlserver/data
    networks:
      - my-network

  consul:
    image: "consul"
    container_name: consul
    ports:
      - 8500:8500
    networks:
      - my-network

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: api-gateway
    build: 
      context: .
      dockerfile: APIGateway/Dockerfile   
    ports:
      - 9000:80
      - 9001:443
    networks:
      - my-network
    depends_on:
      - consul

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    container_name: 'auth-service'
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    networks:
      - my-network
    depends_on:
      - consul
      - db

  customersapiservices:
    image: ${DOCKER_REGISTRY-}customersapiservices
    container_name: 'customer-instance1'
    build:
      context: .
      dockerfile: CustomersAPIServices/Dockerfile
    ports:
      - 1000:80
      - 1100:443
    networks:
      - my-network
    depends_on:
      - consul

  customersapiservices2:
    image: ${DOCKER_REGISTRY-}customersapiservices
    container_name: 'customer-instance2'
    build:
      context: .
      dockerfile: CustomersAPIServices/Dockerfile
    ports:
      - 1001:80
      - 1101:443
    networks:
      - my-network
    depends_on:
      - consul


  productsapiservices:
    image: ${DOCKER_REGISTRY-}productsapiservices
    container_name: 'product-instance1'
    build:
      context: .
      dockerfile: ProductsAPIServices/Dockerfile
    ports:
      - 2000:80
      - 2100:443
    networks:
      - my-network
    depends_on:
      - consul

  productsapiservices2:
    image: ${DOCKER_REGISTRY-}productsapiservices
    container_name: 'product-instance2'
    build:
      context: .
      dockerfile: ProductsAPIServices/Dockerfile
    ports:
      - 2001:80
      - 2101:443
    networks:
      - my-network
    depends_on:
      - consul

  productsapiservices3:
    image: ${DOCKER_REGISTRY-}productsapiservices
    container_name: 'product-instance3'
    build:
      context: .
      dockerfile: ProductsAPIServices/Dockerfile
    ports:
      - 2002:80
      - 2102:443
    networks:
      - my-network
    depends_on:
      - consul
